DATA_FILE: "src/example_dataset_trics.csv"
TOP_FOLDER: "out/"
N_CLUST: 3
MIN_APP: 5
REF_FEATURE: "individual_name"
INCLUDE_STATIC: False
STATIC_FEATURES: {
                  'Gender':'categorical',
                  'Age_onset':'continuos',
                  'UMNvsLMN':'categorical',
                  'C9orf72':'categorical',
                  'BMI_at_1st_visit': continuos,
                  'Diagnostic Delay': continuos,
                  'Onset_form': 'categorical'
                }

TEMPORAL_FEATURES: {
                  'S_0':'continuos',
                  'S_1':'continuos',
                  'S_2':'continuos',
                  'S_3':'continuos',
                  'S_4':'continuos',
                  'S_5':'continuos',
                  'S_6':'continuos',
                  'S_7':'continuos',
                  'S_8':'continuos',
                  'S_9':'continuos'
                  }